# Generated by Django 4.2.3 on 2023-08-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
