# Generated by Django 4.2.3 on 2023-08-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineas', '0005_avion_aeropuerto_destino_avion_aeropuerto_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='aeropuerto_destino',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='aeropuerto_origen',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='aeropuerto_destino',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='aeropuerto_origen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
